//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sor.Models.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionDocenteEntities : DbContext
    {
        public GestionDocenteEntities()
            : base("name=GestionDocenteEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<Psicologos> Psicologos { get; set; }
        public virtual DbSet<DocenteScore> DocenteScore { get; set; }
        public virtual DbSet<MotivosRechazo> MotivosRechazo { get; set; }
        public virtual DbSet<TernasxModulo> TernasxModulo { get; set; }
        public virtual DbSet<DocenteMateria> DocenteMateria { get; set; }
        public virtual DbSet<DepartamentosAcademicos> DepartamentosAcademicos { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
    }
}
